apiVersion: apps/v1
kind: Deployment
metadata:
  name: obf-redis
  namespace: efk
spec:
  selector:
    matchLabels:
      app: obf-redis
  replicas: 1
  template:
    metadata:
      labels:
        app: obf-redis
    spec:
      containers:
      - name: master
        image: redis:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 6379
        
    
---
apiVersion: v1
kind: Service
metadata:
  name: obf-redis
  namespace: efk
spec:
  ports:
  - port: 6379
  selector:
    app: obf-redis
