apiVersion: v1
kind: Service
metadata:
  name: obf-keycloak
  namespace: efk
  labels:
    app: obf-keycloak
    name: obf-keycloak
spec:
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 8080
      nodePort: 30202
  selector:
    app: obf-keycloak
    
---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: obf-keycloak
  namespace: efk
  labels:
    app: obf-keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: obf-keycloak
  template:
    metadata:
      labels:
        app: obf-keycloak
    spec:
      containers:
      - name: obf-keycloak
        image: jboss/keycloak
        env:
        - name: KEYCLOAK_USER
          value: "admin"
        - name: KEYCLOAK_PASSWORD
          value: "admin"
        - name: DB_USERNAME
          value: "keycloak"
        - name: DB_PASSWORD
          value: "keycloak"
        - name: DB_VENDOR
          value: "MYSQL"
        - name: connectTimeout
          value: "6000000"
        - name: MYSQL_PORT
          value: "3306"
        - name: DB_ADDR
          value: "obf-mysql"
        - name: JGROUPS_DISCOVERY_PROTOCOL
          value: kubernetes.KUBE_PING
        - name: JGROUPS_DISCOVERY_PROPERTIES
          value: 'port_range=0,dump_requests=true'
        - name: PROXY_ADDRESS_FORWARDING
          value: 'true' 
        - name: JDBC_PARAMS
          value: "useSSL=false"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
