apiVersion: v1
kind: Service
metadata:
  name: obf-mysql
  namespace: efk
spec:
  ports:
  - port: 3306
  selector:
    app: obf-mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: obf-mysql
  namespace: efk
spec:
  selector:
    matchLabels:
      app: obf-mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: obf-mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: root
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv1-claim
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv1-volume
  namespace: efk
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/ist/obfmysqlPV"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv1-claim
  namespace: efk
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

