server:
  port: 8082
 
#Keycloak Configuration
keycloak:
  #  auth-server-url: http://35.228.3.174/auth
  auth-server-url: http://http://35.225.3.232/auth
  realm: master
  resource: Demo
  principal-attribute: preferred_username
  public-client: true
  
#~ kc:
  #~ base-url: http://192.168.4.248:8080/auth
  #~ realm: activiti
  #~ realm-url: ${kc.base-url}/realms/${kc.realm}
  #~ username: admin
  #~ userpass: admin
  #~ client-id: activiti
  #~ assignee-role: agent
  

spring:
  profiles:
    active: default #: to run application.yml file    &&  prod : to run application-prod.yml file
    redis:
    host: redis
    port: 6379
  jpa:
    database: mysql
    show-sql: false
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  datasource:
    platform: mysql
    url: jdbc:mysql://mysql:3306/rusdn
    #?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=AEST
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    initialization-mode: always
    
    
logfile:
   basePath: /home/ist/DOCUMENTS/logfileDoc/
   enodeBIds: ENODEB-1|ENODEB-2|ENODEB-3
   noOfDays: 10
   elasticHost: http://192.168.105.124
   elasticPort: 30105

logging:
  level:
    root: info
    org.springframework.web: info
    org.hibernate: none
  file: ./logfile.log
